### ISSUE TITLE
Running Tests with Pytest

### ISSUE THREAD

**Issue by mexicantexan** [faisalnazik/Django-REST-Framework-React-BoilerPlate#34]
**Describe the bug**
Django errors out  with ```django.core.exceptions.ImproperlyConfigured: Requested setting DATABASES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before access
ing settings.``` when running pytest.

**To Reproduce**
1. install project
2. navigate to {PROJECT_DIRECTORY}/backend
3. run `python -m pytest`

**Expected behavior**
Pytest to pass out of the box

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A
 - Version: Latest

**Suggested Fix**
```
import os
import django

if not settings.configured:
    os.environ['DJANGO_SETTINGS_MODULE'] = 'config.settings'
    django.setup()
```

could be added to backend/accounts/tests.py

**Comment by mexicantexan** [comment]
Doesn't have to be included, just nice for people in the Pytest cult like me.

**Comment by faisalnazik** [comment]
Ok, Thanks for the suggested fix. Will review and provide the feedback. ASAP

**Comment by faisalnazik** [comment]
@mexicantexan Hey, check out the updated config for `pytest`. It's resolved.
