### ISSUE TITLE
inssue while installing the backend pycog2 needs to updated to pycog2 binary

### ISSUE THREAD

**Issue by sarangkkl** [faisalnazik/Django-REST-Framework-React-BoilerPlate#36]
**Describe the bug**

**To Reproduce**
1. Go to ''backend folder  and then create a virtual env
2. run pip install'
3. it gives error packages not able to installed

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by faisalnazik** [comment]
I can't understand why that needs to be updated to binary. According to official Documentation. 

> The psycopg2-binary package is meant for beginners to start playing with Python and PostgreSQL without the need to meet the build requirements.
> If you are the maintainer of a published package depending on psycopg2 you shouldn’t use psycopg2-binary as a module dependency.

[Source ](https://www.psycopg.org/docs/install.html#:~:text=psycopg%20vs%20psycopg-binary,binary%20as%20a%20module%20dependency.)
